version: '3'
services:
  front:
    build: .
    command: npm run serve
    ports:
      - 8888:8080

    volumes:
      - ./vueproject:/app
      - ./vueproject/n_modules:/app/node_modules
    stdin_open: true
    tty: true



